### PR TITLE
Myvr/use utc in db

### PR DESCRIPTION
**Pull request by GeorgeSpark-Stahl**
This change is [Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/2)

### CODE REVIEW

**Review by GeorgeSpark-Stahl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/2)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jkasky)

___
*[django_celery_beat/schedulers.py, line 104 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/2#-LZuPCxX8ppOVYdKor3R:-LZuPCxY7dM6ajRdgcIQ:bubuc65) ([raw file](https://github.com/myvr/django-celery-beat/blob/d355a3ffa716da2968ba207b48210130132b0a0f/django_celery_beat/schedulers.py#L104)):*
> ```Python
>     def _default_now(self):
>         return now()
>         
> ```

Fixing this whitespace.

**Review by jkasky — COMMENTED** [review]
Did you take a look at where the upstream django_celery_project is at? I see some interesting changes: specifically this PR https://github.com/celery/django-celery-beat/pull/203

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/2#-:-LZuVkOM8GOCBLuDIkBY:bv79hfd)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jkasky)

**Review by GeorgeSpark-Stahl — COMMENTED** [review]
I looked at it briefly - I think it would run into the same problem during DST because the naive times would get localized using the current timezone.  It wouldn't crash though, I don't think.

I also became sad because in the next version of beat after ours they require django 1.11: https://github.com/celery/django-celery-beat/blob/master/Changelog

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/2#-:-LZukEps3fC1Qdw49wUb:bii6p3w)* status: 1 of 4 files reviewed, all discussions resolved

**Review by GeorgeSpark-Stahl — COMMENTED** [review]
One thing I noticed(unrelated to above) is that django-celery-beat seems to only read/write from the database when there are changes it can detect, so if it's running when we update the last_run_at timestamp it may ignore it and then overwrite it the next time it decides to touch the db.

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/2#-:-LZukjte7CVv6fM-MZYj:b-szdsfw)* status: 1 of 4 files reviewed, all discussions resolved

**Review by GeorgeSpark-Stahl — COMMENTED** [review]
Also this may be chicken scratches without the context I was using to create it, but here is a document I created when trying to understand how times flow around:  https://drive.google.com/file/d/1PRcH9Mk2yqYgI4PiMBYonbgPG-gcSRkx/view?usp=sharing

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/2#-:-LZulH-OB2zbagJ6ONmw:bjak40f)* status: 1 of 4 files reviewed, all discussions resolved

**Review by jkasky — APPROVED** [review]
OK, that's good to know, we should take celerybeat down before deploy just in-case.

> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/2#-:-LZv2YJhAuadfVSaWj72:bljn13n)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jkasky — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/2#-:-LZv2pq03ViLhrZAJsDH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
